version: '3.7'
services:
  nginx_app:
    image: nginx:latest
    depends_on:
      - flask_cpu
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - my_project_network
  
  flask_cpu:
    build:
      context: ./cpu
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - my_project_network

networks:
  my_project_network:
    external: true