version: '3.7'
services:
  nginx_app:
    image: nginx:latest
    depends_on:
      - flask_cpu
      - flask_memory
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 8090:81
    networks:
      - my_project_network
  
  flask_cpu:
    build:
      context: ./cpu
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - my_project_network

  flask_memory:
    build:
      context: ./memory
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - my_project_network

networks:
  my_project_network:
    external: true