name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create network
      run: docker network create --driver=bridge my_project_network
    - name: Build the Docker image
      run: docker-compose up --build -d
    - name: test CPU
      run: curl 0.0.0.0:8080
    - name: test MEMORY
      run: curl 0.0.0.0:8090
    - name: Stop Docker
      run: docker-compose down
